name: Check build and deploy project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    uses: grimeoverhere/github-workflows/.github/workflows/build_maven_check.yml@main
    secrets: inherit

  deploy:
    if: github.event_name == 'workflow_dispatch'
    uses: grimeoverhere/github-workflows/.github/workflows/build_and_deploy.yml@main
    secrets: inherit